### ISSUE TITLE
Working example

### ISSUE THREAD

**Issue by aHumanBeing** [tphuocthai/passport-ldapjs#1]
Hi,

I'm struggling to piece this together with my first web app.  Do you have a working example I could look at?

Thank you

**Comment by tphuocthai** [comment]
What is the problem you have? The example from README file is working. I have tested with OpenLDAP and Windows Active Directory 2013.

**Comment by aHumanBeing** [comment]
Thanks for getting back so soon!  Basically, I'm following your readme but I'm still missing what goes in index.js etc...I'm trying to reference http://passportjs.org/docs for guidance.  Also, if this was the wrong place to ask then please forgive me.  I'm new to this area.

**Comment by tphuocthai** [comment]
You should familiar with passportjs first.
Thanks
