### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by jcheng5** [tphuocthai/passport-ldapjs#2]
I'm not a user of this library (we implemented something similar before it was available) but stumbled onto it when trying to fix some bugs in our own similar implementation. I hope you find these helpful.

* It's necessary to listen on the `"error"` event on the ldapjs client object; low-level networking errors are surfaced using this event. However, note that depending on timing you may receive an event even after you've successfully (or unsuccessfully) attempted to auth. Also, note that there's also a `"connectTimeout"` event, I haven't seen that in the wild but it's there in the ldapjs source code.
* I don't see you calling `unbind()` on the ldapjs client; you should do this after using the client so you can free up the network connection and also stop other downstream objects from being leaked.
* I don't remember the details but we had to pay a lot of attention to escaping values that are being inserted into LDAP search query strings. And even after a bunch of time spent on it there are edge cases we don't deal with well. But there may even be security implications if you don't do any escaping at all (sorry, again, I don't remember the details but think sql injection style attacks).

**Comment by tphuocthai** [comment]
@jcheng5,

Sorry I did not login using this account for a long time and thank you very much for your suggestion. Totally agree with you.

Currently I'm not working on this project anymore, so don't have any resources to test implement as your suggestion.

Any PRs is highly appreciate from anyone

Thanks you very much
