### ISSUE TITLE
No differentiation between "bind" user and "search" user

### ISSUE THREAD

**Issue by MelwinKfr** [tphuocthai/passport-ldapjs#3]
I'm currently facing to an LDAP security strategy which doesn't allow every user to search, it requires to be an admin user.

At [this line](https://github.com/tphuocthai/passport-ldapjs/blob/master/lib/strategy.js#L70) you use the user account to bind the LDAP server, which is not authorized in my current configuration.

What I suggest is to provide two other optional options:
- bindUser
- bindPassword

But you could also use a different DN request to bind LDAP servers.

**Comment by tphuocthai** [comment]
Thank you @MelwinKfr, your PR looks great

**Comment by MelwinKfr** [comment]
No problem, you're welcome. Do you think it would be possible to generate a new patch version number for this ?

**Comment by tphuocthai** [comment]
Yes, I just publish new patch version 1.0.3 to npm repo

**Comment by MelwinKfr** [comment]
Thanks a lot !
